---
title: "DM2-EDA"
output: html_document
date: "`r Sys.Date()`"
---

```{r}
library(readr)
#read dataset
data <- read_csv("dataset/training_v2.csv/training_v2.csv")
dim(data)
```

#Data Preparation/Cleaning
```{r}
#remove the id columns from dataset
data$encounter_id <- NULL
data$hospital_id <- NULL
data$patient_id <- NULL
#drop variables which has null values more than 15%
data <- data[, which(colMeans(is.na(data)) < 0.15)]
dim(data)
```

```{r}
#summary of dataset
summary(data)
```

```{r}
#Combining categories with less than 5% observations into one
data$ethnicity[data$ethnicity == "Native American" | data$ethnicity== "Asian" | data$ethnicity == "Hispanic"] <- "Other/Unknown"
data$icu_admit_source[data$icu_admit_source == "Other Hospital" | data$icu_admit_source == "Other ICU"] <- "other"
#Replacing duplicate factor label with one single label
data$apache_2_bodysystem[data$apache_2_bodysystem == 'Undefined diagnoses'] <- 'Undefined Diagnoses'

#Factoring
data$ethnicity = as.factor(data$ethnicity)
data$icu_admit_source = as.factor(data$icu_admit_source)
data$gender = as.factor(data$gender)
data$icu_stay_type = as.factor(data$icu_stay_type)
data$apache_2_bodysystem = as.factor(data$apache_2_bodysystem)
data$icu_type = as.factor(data$icu_type)
data$apache_3j_bodysystem = as.factor(data$apache_3j_bodysystem)
summary(data)
```

```{r}
#Manul binarization
library(caret)
vars.categorical <- c("ethnicity","icu_admit_source","gender","icu_stay_type","apache_2_bodysystem","apache_3j_bodysystem")
binarizer <- dummyVars(paste("~", paste(vars.categorical, collapse = "+")),
                        data = data_new, fullRank = TRUE)
binarized_vars <- data.frame(predict(binarizer, newdata = data_new))
data_new <- cbind(data_new, binarized_vars)
data_new$ethnicity <- NULL
data_new$icu_admit_source <- NULL
data_new$gender <- NULL
data_new$icu_stay_type <- NULL
data_new$apache_2_bodysystem <- NULL
data_new$apache_3j_bodysystem <- NULL
summary(data_new)
```

```{r}
#Save the names of the factor variables as a vector
#Relevel
vars.cat <- c("ethnicity","icu_admit_source","gender","icu_stay_type","apache_2_bodysystem","apache_3j_bodysystem")

for (i in vars.cat){
  table <- as.data.frame(table(data[, i]))
  max <- which.max(table[, 2])
  level.name <- as.character(table[max, 1])
  data[, i] <- relevel(data[, i], ref = level.name)
}
```

```{r}
library(glmnet)
#Applying regularization for feature selection
X.train <- subset(data_new, select=-hospital_death)
m.lambda <- glmnet(x = X.train,
                   y = data_new$hospital_death,
                   family = "binomial",
                   nfold=10,
                   lambda = 1:20,
                   alpha=1)
print(m.lambda)
```

```{r}
library("dplyr")
#generate correlation plot
#data.numeric <- data[,unlist(lapply(data, is.numeric))]
cor.matrix <- cor(data.numeric[1:10], use = "complete.obs")
data <- round(cor.matrix, digits=4)
print(data)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
